<a href="https://colab.research.google.com/github/FredyVG15/Entregas-/blob/main/Tarea_M%C3%A9todo_Uniformizaci%C3%B3n.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**MÉTODO DE UNIFORMIZACIÓN**


#Primer Problema a resolver

3. **Teorema (matriz $P(t)$):** La matriz de probabilidad de transición $P(t) = [p_{i,j}(t)]$ está dada por

$$P(t) = \sum_{k=0}^{\infty} e^{-rt} \frac{(rt)^k}{k!} \hat{P}^k$$

3. **(Ejercicio)** Este último teorema permite aproximar $P(t)$ usando los primeros $M$ términos de la serie infinita. Se obtienen buenos resultados si se elige

$$M \approx \max \{rt + 5\sqrt{rt},\; 20\}$$

1. Use esta propuesta para calcular $P(0.5)$, $P(1)$ y $P(5)$ para la matriz $R$ del ejercicio 1. Es decir:

 $$R = \begin{pmatrix}
0 & 2 & 3 & 0 \\
4 & 0 & 2 & 0 \\
0 & 2 & 0 & 2 \\
1 & 0 & 3 & 0
\end{pmatrix}$$



In [31]:
import numpy as np # Importamos NumPy para trabajar con matrices y operaciones numéricas
import math # Importamos math para usar funciones matemáticas como exp, sqrt, etc.

In [32]:

# Definimos la matriz de tasas R de la Cadena de Markov a Tiempo Continuo
R = np.array([
    [0, 2, 3, 0],
    [4, 0, 2, 0],
    [0, 2, 0, 2],
    [1, 0, 3, 0]
], dtype=float) # dtype=float permite trabajar con decimales



In [33]:

# Calculamos r_i, que es la suma de cada renglón de R
ri = R.sum(axis=1)
# Elegimos r como el máximo de los valores r_i
# r = max{r_i}
r = ri.max()

In [34]:

# Construimos P sombrero
# Construimos inicialmente P_som dividiendo cada entrada de R entre r
P_som = R / r


# Ajustamos la diagonal de P_som
for i in range(len(R)):

  # En la diagonal usamos la fórmula: 1 - r_i/r
    P_som[i, i] = 1 - ri[i] / r

print("r =", r)# Mostramos el valor de r
print("\nP_som =")# Mostramos la matriz P_som
print(P_som)

r = 6.0

P_som =
[[0.16666667 0.33333333 0.5        0.        ]
 [0.66666667 0.         0.33333333 0.        ]
 [0.         0.33333333 0.33333333 0.33333333]
 [0.16666667 0.         0.5        0.33333333]]


In [35]:

# Definimos una función para calcular P(t)

def calcular_P(t):
    # Elegir M con la regla dada
    M = math.ceil(max(r*t + 5*math.sqrt(r*t), 20)) # Calculamos M con la regla: M ≈ max{rt + 5sqrt(rt), 20}

    # Inicializar matriz resultado
    P_t = np.zeros_like(R) # Creamos una matriz de ceros del mismo tamaño que R

    # Potencia inicial P_som^0 = I
    potencia = np.eye(len(R)) # La primera potencia es P_som^0, que es la matriz identidad

    # Primer coeficiente: e^(-rt)
    coef = math.exp(-r*t) # El primer coeficiente de la serie corresponde a k=0

    # Suma de la serie
    for k in range(M + 1):# Sumamos los términos desde k=0 hasta k=M

    # Para k mayor que 0 actualizamos la potencia y el coeficiente
        if k > 0:
            potencia = potencia @ P_som # Calculamos la siguiente potencia: P_som^k

             # Actualizamos el coeficiente de Poisson:
            # e^(-rt)(rt)^k/k!
            coef = coef * (r*t) / k

        P_t = P_t + coef * potencia # Agregamos el término actual de la serie

    return P_t, M # Regresamos la matriz P(t) aproximada y el valor de M usado

In [36]:
# Calculamos P(0.5), P(1), P(5)
P_05, M_05 = calcular_P(0.5)
P_1, M_1 = calcular_P(1)
P_5, M_5 = calcular_P(5)

print("\nM para t=0.5:", M_05)
print("P(0.5) =")
print(np.round(P_05, 6))

print("\nM para t=1:", M_1)
print("P(1) =")
print(np.round(P_1, 6))

print("\nM para t=5:", M_5)
print("P(5) =")
print(np.round(P_5, 6))



M para t=0.5: 20
P(0.5) =
[[0.250609 0.216965 0.386657 0.14577 ]
 [0.253135 0.238361 0.374409 0.134095]
 [0.169119 0.193615 0.420301 0.216965]
 [0.158017 0.157445 0.398332 0.286206]]

M para t=1: 20
P(1) =
[[0.206151 0.203902 0.39871  0.191236]
 [0.208284 0.205341 0.397899 0.188474]
 [0.196758 0.198379 0.400959 0.203902]
 [0.192046 0.193997 0.401471 0.212484]]

M para t=5: 58
P(5) =
[[0.2      0.2      0.399999 0.2     ]
 [0.2      0.2      0.399999 0.2     ]
 [0.2      0.2      0.399999 0.2     ]
 [0.2      0.2      0.399999 0.2     ]]


2. ¿Se verifica la ecuación de Chapman-Kolmogorov $P(1) = P(0.5)P(0.5)$?

In [37]:
# Verificar Chapman-Kolmogorov
producto = P_05 @ P_05

print("\nP(0.5)P(0.5) =")
print(np.round(producto, 6))

print("\nDiferencia P(1) - P(0.5)P(0.5) =")
print(np.round(P_1 - producto, 8))




P(0.5)P(0.5) =
[[0.206151 0.203902 0.39871  0.191236]
 [0.208285 0.205341 0.3979   0.188475]
 [0.196759 0.19838  0.400959 0.203902]
 [0.192047 0.193997 0.401472 0.212485]]

Diferencia P(1) - P(0.5)P(0.5) =
[[-2.9e-07 -2.9e-07 -5.8e-07 -2.9e-07]
 [-2.9e-07 -2.9e-07 -5.8e-07 -2.9e-07]
 [-2.9e-07 -2.9e-07 -5.8e-07 -2.9e-07]
 [-2.9e-07 -2.9e-07 -5.8e-07 -2.9e-07]]


Para Chapman-Kolmogorov:
P(1) ≈ P(0.5)P(0.5)

El error máximo absoluto es del orden de:5.82e-07

Sí se cumple porque una CMTC homogénea tiene la propiedad de semigrupo:

$$P(t+s)=P(t)P(s)$$

Esta es precisamente la ecuación de Chapman-Kolmogorov.

Tomando:

$$t=0.5,\quad s=0.5$$

se obtiene:

$$P(0.5+0.5)=P(0.5)P(0.5)$$

por lo tanto:

$$P(1)=P(0.5)P(0.5)$$

Analíticamente, para cada entrada $(i,j)$:

$$p_{ij}(1)=P(X(1)=j \mid X(0)=i)$$

Insertamos un estado intermedio $k$ en el tiempo $0.5$:

$$p_{ij}(1)=\sum_{k=1}^{N} P(X(1)=j,\; X(0.5)=k \mid X(0)=i)$$

Usando probabilidad condicional:

$$p_{ij}(1)=\sum_{k=1}^{N} P(X(1)=j \mid X(0.5)=k,\; X(0)=i)\; P(X(0.5)=k \mid X(0)=i)$$

Por la propiedad de Markov:

$$P(X(1)=j \mid X(0.5)=k,\; X(0)=i)=P(X(1)=j \mid X(0.5)=k)$$

Y como la cadena es homogénea en el tiempo:

$$P(X(1)=j \mid X(0.5)=k)=P(X(0.5)=j \mid X(0)=k)=p_{kj}(0.5)$$

Entonces:

$$p_{ij}(1)=\sum_{k=1}^{N} p_{ik}(0.5)\; p_{kj}(0.5)$$

Pero esa suma es exactamente la entrada $(i,j)$ del producto matricial:

$$[P(0.5)P(0.5)]_{ij}=\sum_{k=1}^{N} p_{ik}(0.5)\; p_{kj}(0.5)$$

Por tanto:

$$p_{ij}(1)=[P(0.5)P(0.5)]_{ij}$$

y, en forma matricial:

$$P(1)=P(0.5)P(0.5)$$

#Segundo Problema a resolver
4. **Teorema (Cotas de error para $P(t)$):** Para un $t \geq 0$ fijo, sea

$$P^M(t) = [p_{i,j}^M(t)] = \sum_{k=0}^M e^{-rt} \frac{(rt)^k}{k!} \hat{P}^k$$

entonces $|p_{i,j}(t) - p_{i,j}^M(t)| \leq \sum_{k=M+1}^\infty e^{-rt} \frac{(rt)^k}{k!}$ para todo $1 \leq i, j \leq N$.


2. **(Ejercicio)** Este teorema se puede usar así: Suponga que se desea calcular $P(t)$ con una tolerancia $\epsilon$. Elija $M$ tal que

$$\sum_{k=M+1}^\infty e^{-rt} \frac{(rt)^k}{k!} \leq \epsilon$$

Y se puede implementar de acuerdo al siguiente algoritmo de uniformización para $P(t)$:

   1. Dados $R$, $t$, $0 < \epsilon < 1$.
   2. Calcular $r$ usando la igualdad en la definición.
   3. Calcular $\hat{P}$.
   4. $A = \hat{P}$; $B = e^{-rt}$; $c = e^{-rt}$; $sum = c$; $k = 1$
   5. Mientras $sum < 1 - \epsilon$ hacer:

      $$c = c \cdot (rt)/k$$

      $$B = B + cA$$

      $$A = A \hat{P}$$

      $$sum = sum + c$$

      $$k = k + 1$$

   6. $B$ está a $\epsilon$ de $P(t)$.

Repita el ejercicio 3 aplicando este algoritmo con una tolerancia $\epsilon = 0.00001$ (indique el valor correspondiente de $M$ en cada caso). Compare los resultados.

2) Programa que repite el ejercicio 3 con ϵ=0.00001

In [38]:
# Importamos NumPy para trabajar con matrices
import numpy as np
# Importamos math para usar funciones matemáticas como exp, sqrt
import math

In [39]:
# Definimos la matriz de tasas R de la cadena de Markov en tiempo continuo
R = np.array([
    [0, 2, 3, 0],
    [4, 0, 2, 0],
    [0, 2, 0, 2],
    [1, 0, 3, 0]
], dtype=float)

epsilon = 0.00001 # Definimos la tolerancia epsilon

In [40]:
# Calculamos r_i y r:
ri = R.sum(axis=1)# Calculamos r_i, que es la suma de cada renglón de R
r = ri.max() # Calculamos r como el máximo de los valores r_i

# Construir P_som
P_som = R / r # Construimos inicialmente P_som dividiendo cada entrada de R entre r

In [41]:
#Ciclo para querRecorremos cada renglón de la matriz
for i in range(len(R)):
    P_som[i, i] = 1 - ri[i] / r # Modificamos la diagonal usando la fórmula 1 - r_i/r

In [42]:
#ALGORITMO PARA USAR LA TOLERANCIA ÉPSILON

# Definimos una función para calcular P(t) usando la tolerancia epsilon
def P_con_tolerancia(t, epsilon):

    n = len(R)  # Guardamos el número de estados de la cadena

     # Inicializamos A como una copia de P_som

    A = P_som.copy()  #A irá guardando las potencias de P_som

    # Inicializamos B con el primer término de la serie:
    # e^(-rt) * I
    B = math.exp(-r*t) * np.eye(n)

    # Calculamos el primer coeficiente de Poisson:
    # c_0 = e^(-rt)
    c = math.exp(-r*t)

    suma = c # Inicializamos la suma acumulada de probabilidades Poisson

    k = 1 # Inicializamos k en 1 porque ya usamos el término k=0

    #Ciclo que repetimos mientras la suma acumulada sea menor que 1 - epsilon

    while suma < 1 - epsilon:

 # Calculamos el siguiente coeficiente:
        # c_k = c_{k-1} * (rt)/k
        c = c * (r*t) / k

        # Sumamos el nuevo término de la serie:
        B = B + c * A  # B = B + c_k * P_som^k

       # Actualizamos A para obtener la siguiente potencia de P_som
        A = A @ P_som

        suma = suma + c # Actualizamos la suma acumulada de probabilidades Poisson

        k = k + 1 # Incrementamos k para el siguiente término de la serie

         # Como k se incrementa al final del ciclo,
    # el último término usado fue k - 1
    M = k - 1
    error = 1 - suma # La cota del error corresponde a la cola no sumada

    return B, M, error # Regresamos la matriz aproximada, el valor de M y el error

In [43]:
# Definimos una función para calcular P(t)
# usando la regla aproximada del ejercicio 3

# Función del ejercicio 3 usando M aproximado
def P_con_M_aproximado(t):
 # Calculamos M con la fórmula:
    M = math.ceil(max(r*t + 5*math.sqrt(r*t), 20))

    n = len(R) # Guardamos el número de estados
    P_t = np.zeros((n, n)) # Inicializamos P_t como una matriz de ceros
    A = np.eye(n) # Inicializamos A como la identidad
    c = math.exp(-r*t) # Calculamos el primer coeficiente


    # Recorremos desde k=0 hasta k=M
    for k in range(M + 1):


# Si k es mayor que 0, actualizamos potencia y coeficiente
        if k > 0:
            A = A @ P_som  # Actualizamos A para obtener P_som^k
            c = c * (r*t) / k # Actualizamos el coeficiente

        P_t = P_t + c * A # Sumamos el término actual a P_t

    return P_t, M #Regresamos la matriz aproximada y el valor de M usado

In [44]:
#Definimos los tiempos que queremos evaluar
tiempos = [0.5, 1, 5]

for t in tiempos:# Recorremos cada valor de tiempo

    P_tol, M_tol, error = P_con_tolerancia(t, epsilon) # Calculamos P(t) usando el método con tolerancia epsilon
    P_aprox, M_aprox = P_con_M_aproximado(t) # Calculamos P(t) usando el método con M aproximado

    diferencia = np.max(np.abs(P_tol - P_aprox))

    print("\n----------------------------------")
    print("t =", t)

    print("\nMétodo con tolerancia epsilon")
    print("M =", M_tol)
    print("Cota de error =", error)
    print(np.round(P_tol, 6))

    print("\nMétodo con M aproximado del ejercicio 3")
    print("M =", M_aprox)
    print(np.round(P_aprox, 6))

    print("\nDiferencia máxima entre ambos métodos:")
    print(diferencia)


----------------------------------
t = 0.5

Método con tolerancia epsilon
M = 13
Cota de error = 3.4019146132324707e-06
[[0.250608 0.216964 0.386656 0.145769]
 [0.253134 0.23836  0.374408 0.134094]
 [0.169119 0.193614 0.4203   0.216964]
 [0.158017 0.157444 0.39833  0.286205]]

Método con M aproximado del ejercicio 3
M = 20
[[0.250609 0.216965 0.386657 0.14577 ]
 [0.253135 0.238361 0.374409 0.134095]
 [0.169119 0.193615 0.420301 0.216965]
 [0.158017 0.157445 0.398332 0.286206]]

Diferencia máxima entre ambos métodos:
1.3607613894017767e-06

----------------------------------
t = 1

Método con tolerancia epsilon
M = 19
Cota de error = 5.180168936913532e-06
[[0.20615  0.203901 0.398708 0.191235]
 [0.208283 0.20534  0.397898 0.188474]
 [0.196758 0.198379 0.400957 0.203901]
 [0.192045 0.193996 0.401469 0.212483]]

Método con M aproximado del ejercicio 3
M = 20
[[0.206151 0.203902 0.39871  0.191236]
 [0.208284 0.205341 0.397899 0.188474]
 [0.196758 0.198379 0.400959 0.203902]
 [0.192046 0.1

In [45]:
# Verificación Chapman-Kolmogorov con el método de tolerancia
# Calculamos P(0.5) usando el método con tolerancia
P_05, M_05, error_05 = P_con_tolerancia(0.5, epsilon)

# Calculamos P(1) usando el método con tolerancia
P_1, M_1, error_1 = P_con_tolerancia(1, epsilon)

# Calculamos el producto P(0.5)P(0.5)
producto = P_05 @ P_05


print("Verificación Chapman-Kolmogorov")
print("P(1) ≈ P(0.5)P(0.5)")

print("\nP(1) =")
print(np.round(P_1, 6))

print("\nP(0.5)P(0.5) =")
print(np.round(producto, 6))


Verificación Chapman-Kolmogorov
P(1) ≈ P(0.5)P(0.5)

P(1) =
[[0.20615  0.203901 0.398708 0.191235]
 [0.208283 0.20534  0.397898 0.188474]
 [0.196758 0.198379 0.400957 0.203901]
 [0.192045 0.193996 0.401469 0.212483]]

P(0.5)P(0.5) =
[[0.20615  0.203901 0.398707 0.191235]
 [0.208283 0.20534  0.397897 0.188473]
 [0.196757 0.198378 0.400957 0.203901]
 [0.192045 0.193996 0.401469 0.212483]]


Con $\epsilon = 0.00001$, los valores esperados de $M$ son aproximadamente:

$$M_{0.5} = 13,\quad M_{1} = 19,\quad M_{5} = 56.$$

La comparación con el ejercicio 3 es que aquí el algoritmo elige $M$ usando directamente la tolerancia, no con la regla aproximada

$$M \approx \max\{rt + 5\sqrt{rt},\; 20\}.$$

Por eso, para $t = 0.5$ y $t = 1$, este método usa menos términos que la regla anterior, pero mantiene el error menor que:

$$\epsilon = 0.00001.$$

Además, se debe verificar numéricamente que:

$$P(1) \approx P(0.5) P(0.5).$$




El método con tolerancia usa menos términos que el método del ejercicio 3 en $t = 0.5$ y $t = 1$, pero garantiza que la cola Poisson sea menor que:

$$\epsilon = 0.00001.$$

Para $t = 5$, ambos métodos dan resultados prácticamente iguales, aunque pueden usar valores diferentes de $M$.

 $M$ es el número hasta donde cortamos la serie infinita:

$$P(t) = \sum_{k=0}^{\infty} e^{-rt} \frac{(rt)^k}{k!} \hat{P}^k$$

En la práctica no podemos sumar infinitos términos, entonces usamos:

$$P^M(t) = \sum_{k=0}^{M} e^{-rt} \frac{(rt)^k}{k!} \hat{P}^k$$

Es decir, $M$ indica el último valor de $k$ que se suma.

Como en este problema:

$$r = 6$$

entonces para cada tiempo:

$$rt = 6t$$

Por tanto:

$$t = 0.5 \;\Rightarrow\; rt = 3$$
$$t = 1 \;\Rightarrow\; rt = 6$$
$$t = 5 \;\Rightarrow\; rt = 30$$

El algoritmo elige $M$ hasta que la suma acumulada de probabilidades Poisson sea al menos:

$$1 - \epsilon = 1 - 0.00001 = 0.99999$$

Es decir, quiere que la cola que no sumamos sea menor que:

$$\epsilon = 0.00001$$

As que los valores con $\epsilon = 0.00001$ son:

$$M_{0.5} = 13$$

porque para $t = 0.5$, $rt = 3$, y al sumar desde $k = 0$ hasta $k = 13$, la cola restante ya es menor que $0.00001$.

$$M_{1} = 19$$

porque para $t = 1$, $rt = 6$, y se necesita sumar hasta $k = 19$.

$$M_{5} = 56$$

porque para $t = 5$, $rt = 30$, y como el parámetro Poisson es más grande, se necesitan más términos.

| Tiempo (t) | (rt) | (M) con tolerancia (\epsilon=0.00001) |
| ---------: | ---: | ------------------------------------: |
|      (0.5) |  (3) |                                  (13) |
|        (1) |  (6) |                                  (19) |
|        (5) | (30) |                                  (56) |


Mientras más grande es $t$, más grande es $rt$, y por eso se necesitan más términos de la serie.

Entonces, para entender mejor:

$$M_{0.5} = 13$$

significa que usamos:

$$k = 0, 1, 2, \dots, 13$$

para aproximar $P(0.5)$.

$$M_{1} = 19$$

significa que usamos:

$$k = 0, 1, 2, \dots, 19$$

para aproximar $P(1)$.

$$M_{5} = 56$$

significa que usamos:

$$k = 0, 1, 2, \dots, 56$$

para aproximar $P(5)$.

Esto garantiza que el error sea menor que:

$$0.00001.$$

